name = "10x-cards"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-12-09"
compatibility_flags = [ "nodejs_compat" ]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true
